# Generated by Django 4.2.1 on 2023-05-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zergcoach', '0002_buildorder_buildorder_buildorder_matchup'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildorder',
            name='imgur_link',
            field=models.URLField(blank=True),
        ),
    ]
