# Generated by Django 4.2.1 on 2023-05-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zergcoach', '0003_buildorder_imgur_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildorder',
            name='imgur_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
